spring.application.name=proyecto
# Configuración de la base de datos oracle
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XEPDB1
spring.datasource.username=FARMACIA
spring.datasource.password=FARMACIA_PASSWORD
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
# Configuración de JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.open-in-view=false

# Configuración de Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML5
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.servlet.content-type=text/html
spring.thymeleaf.enable-spring-el-compiler=true

server.port=8080


